baseURL = "https://vertlabs.run/"
languageCode = "es"
title = "VertLabs"
theme = "PaperMod"

[params]
  description = "Análisis de rendimiento en trail running"
  ShowReadingTime = true
  ShowShareButtons = true

[[menu.main]]
  name = "Inicio"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Metodología"
  url = "/metodologia/"
  weight = 2